//
// Created by Saman on 24.08.23.
//

#ifndef REALTIME_CELL_COLLAPSE_GLFW_INCLUDE_H
#define REALTIME_CELL_COLLAPSE_GLFW_INCLUDE_H

#define GLFW_INCLUDE_VULKAN

#include <GLFW/glfw3.h>

#endif //REALTIME_CELL_COLLAPSE_GLFW_INCLUDE_H
