//
// Created by Saman on 24.08.23.
//

#ifndef REALTIME_CELL_COLLAPSE_GLM_INCLUDE_H
#define REALTIME_CELL_COLLAPSE_GLM_INCLUDE_H

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_FORCE_LEFT_HANDED
#define GLM_FORCE_MESSAGES

#include <glm/glm.hpp>

#endif //REALTIME_CELL_COLLAPSE_GLM_INCLUDE_H
