//
// Created by Saman on 26.08.23.
//

#ifndef REALTIME_CELL_COLLAPSE_IMGUI_EXAMPLE_H
#define REALTIME_CELL_COLLAPSE_IMGUI_EXAMPLE_H

int imguiExample();

#endif //REALTIME_CELL_COLLAPSE_IMGUI_EXAMPLE_H
